apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/name: system-manager
    app.kubernetes.io/instance: service
    app.kubernetes.io/component: system-manager
    app.kubernetes.io/part-of: backbone
  name: system-manager
spec:
  ports:
  - name: system-manager
    protocol: TCP
    port: 9092
  selector:
    app.kubernetes.io/part-of: backbone
    app.kubernetes.io/name: system-manager
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/name: system-manager-external
    app.kubernetes.io/instance: service
    app.kubernetes.io/component: system-manager
    app.kubernetes.io/part-of: backbone
  name: system-manager-external
spec:
  type: NodePort
  ports:
  - name: system-manager
    protocol: TCP
    port: 9092
    nodePort: 30192
  selector:
    app.kubernetes.io/part-of: backbone
    app.kubernetes.io/name: system-manager
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/name: system-manager
    app.kubernetes.io/instance: deployment
    app.kubernetes.io/component: system-manager
    app.kubernetes.io/part-of: backbone
  name: system-manager
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: system-manager
  replicas: 1
  template:
    metadata:
      labels:
        app.kubernetes.io/name: system-manager
        app.kubernetes.io/instance: deployment
        app.kubernetes.io/component: system-manager
        app.kubernetes.io/part-of: backbone
    spec:
      securityContext:
        runAsUser: 1000
        runAsGroup: 1000
        fsGroup: 1000
      initContainers:
        - name: init-redis
          image: cloud.canister.io:5000/ale8193/busybox
          command: ['sh', '-c', "until nslookup redis.$(cat /var/run/secrets/kubernetes.io/serviceaccount/namespace).svc.cluster.local; do echo waiting for redis service; sleep 2; done"]
        - name: init-redis-shared-memory
          image: cloud.canister.io:5000/ale8193/busybox
          command: [ 'sh', '-c', "until nslookup redis-shared-memory.$(cat /var/run/secrets/kubernetes.io/serviceaccount/namespace).svc.cluster.local; do echo waiting for redis service; sleep 2; done" ]
      containers:
#        - image: cloud.canister.io:5000/ale8193/filebeat:7.9.3
#          name: filebeat
#          env:
#            - name: ELK_HOST
#              value: astaffolani.imolab.it
#            - name: ELASTICSEARCH_HOSTS
#              value: astaffolani.imolab.it:9200
#            - name: ENV_HOST
#              valueFrom:
#                fieldRef:
#                  fieldPath: metadata.namespace
#          envFrom:
#            - secretRef:
#                name: elasticsearch-secret
#          volumeMounts:
#            - mountPath: /var/log/system_manager
#              name: logs
#            - name: filebeat-config
#              mountPath: /usr/share/filebeat/filebeat.yml
#              subPath: filebeat.yml
#              readOnly: true
#          securityContext:
#            runAsUser: 0
#          resources:
#            limits:
#              memory: 200Mi
#            requests:
#              cpu: 100m
#              memory: 100Mi
        - image: cloud.canister.io:5000/ale8193/system_manager
          name: system-manager
          imagePullPolicy: Always
          ports:
            - containerPort: 9092
          env:
            - name: SYSTEM_MANAGER_SERVER_MODULE
              value: rlq_scheduler.system_manager.server
            - name: SYSTEM_MANAGER_SERVER_CONFIG_FILENAME
              value: /opt/rlq/system_manager/config/system_manager.yml
            - name: SYSTEM_MANAGER_MULTI_RUN_CONFIG_FILENAME
              value: /opt/rlq/system_manager/config/multi_run_config.yml
            - name: GLOBAL_CONFIG_FILENAME
              value: /opt/rlq/system_manager/config/global.yml
            - name: BROKER_SERVICE_SERVICE_HOST
              value: redis.default
          envFrom:
            - secretRef:
                name: minio-secret
            - configMapRef:
                name: minio-config
            - configMapRef:
                name: mongo-config
            - secretRef:
                name: mongo-secret
          volumeMounts:
            - name: global-config
              mountPath: /opt/rlq/system_manager/config/global.yml
              subPath: global.yml
              readOnly: true
            - name: system-manager-config
              mountPath: /opt/rlq/system_manager/config/system_manager.yml
              subPath: system_manager.yml
              readOnly: true
            - name: run-config
              mountPath: /opt/rlq/system_manager/config/run_config.yml
              subPath: run_config.yml
              readOnly: true
            - name: multi-run-config
              mountPath: /opt/rlq/system_manager/config/multi_run_config.yml
              subPath: multi_run_config.yml
              readOnly: true
            - name: logs
              mountPath: /opt/rlq/system_manager/logs/system_manager
      volumes:
        - name: global-config
          configMap:
            name: global-config
        - name: system-manager-config
          configMap:
            name: system-manager-config
        - name: run-config
          configMap:
            name: run-config
        - name: multi-run-config
          configMap:
            name: multi-run-config
        - name: logs
          emptyDir: {}
#        - name: filebeat-config
#          configMap:
#            name: filebeat-config
      imagePullSecrets:
        - name: docker-registry