---
apiVersion: v1
kind: Service
metadata:
  name: redis-shared-memory
  labels:
    app.kubernetes.io/name: redis
    app.kubernetes.io/instance: service
    app.kubernetes.io/component: communication
    app.kubernetes.io/part-of: redis
spec:
  ports:
  - port: 6380
    targetPort: 6379
  selector:
    app.kubernetes.io/name: redis-shared-memory
    app.kubernetes.io/instance: deployment
    app.kubernetes.io/component: communication
    app.kubernetes.io/part-of: redis
---
apiVersion: v1
kind: Service
metadata:
  name: redis-shared-memory-external
  labels:
    app.kubernetes.io/name: redis-external
    app.kubernetes.io/instance: service
    app.kubernetes.io/component: communication
    app.kubernetes.io/part-of: redis
spec:
  ports:
  - port: 6379
    targetPort: 6379
    nodePort: 30381
  selector:
    app.kubernetes.io/name: redis-shared-memory
    app.kubernetes.io/part-of: redis
  type: NodePort
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: redis-shared-memory-config
  labels:
    app.kubernetes.io/name: redis-shared-memory
    app.kubernetes.io/instance: config
    app.kubernetes.io/component: communication
    app.kubernetes.io/part-of: redis
data:
  redis.conf: |+
    appendonly yes
    # remove if you want prevent accessing from outside localhost
    protected-mode no
    notify-keyspace-events KA
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis-shared-memory
  labels:
    app.kubernetes.io/name: redis-shared-memory
    app.kubernetes.io/instance: deployment
    app.kubernetes.io/component: communication
    app.kubernetes.io/part-of: redis
spec:
  replicas: 1
  selector:
    matchLabels:
     app.kubernetes.io/name: redis-shared-memory
  template:
    metadata:
      labels:
        app.kubernetes.io/name: redis-shared-memory
        app.kubernetes.io/instance: deployment
        app.kubernetes.io/component: communication
        app.kubernetes.io/part-of: redis
    spec:
      containers:
      - name: leader
        image: cloud.canister.io:5000/ale8193/redis
        resources:
          limits:
            memory: 2Gi
            cpu: 2000m
        ports:
        - containerPort: 6379
        command: ["redis-server", "/conf/redis.conf"]
        volumeMounts:
          - name: conf
            mountPath: /conf
            readOnly: false
      volumes:
        - name: conf
          configMap:
            name: redis-shared-memory-config
            defaultMode: 0755
      imagePullSecrets:
        - name: docker-registry