#!/bin/bash

# gunicorn -k gevent --worker-connections 500 -t 120 -b 0.0.0.0:9092 -u "$SERVER_USER" -g "$SERVER_USER" "$SYSTEM_MANAGER_SERVER_MODULE:create_server('$SYSTEM_MANAGER_SERVER_CONFIG_FILENAME', '$SYSTEM_MANAGER_MULTI_RUN_CONFIG_FILENAME', '$GLOBAL_CONFIG_FILENAME')"

gunicorn -t 600 -w 1 -b 0.0.0.0:9092 "$SYSTEM_MANAGER_SERVER_MODULE:create_server('$SYSTEM_MANAGER_SERVER_CONFIG_FILENAME', '$SYSTEM_MANAGER_MULTI_RUN_CONFIG_FILENAME', '$GLOBAL_CONFIG_FILENAME')"