---

trajectory_builder:
  instances: 1

consumer:
  queue:
    type: redis
    state_creation_key: start_state_creation
    compute_reward_key: compute_reward
    config:
      connection:
        host: redis
        port: 6379
        db: 0

worker_state:
  enabled: false
  update_interval: 0.5  # seconds between each worker state updates
  workers_ping_interval: 5  # seconds between the heartbeat check

logger:
  name: trajectory_collector
  level: 10  # 10=DEBUG, 20=INFO, 30=WARN, 40=ERROR
  handlers:
    - type: console
      parameters: NULL
    - type: file
      parameters:
        log_folder: trajectory_collector
        log_basepath: logs
