version: '3.7'

services:

  mongo:
    image: mongo
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - 27017:27017
    volumes:
      - data:/data/db

  mongo-express:
    image: mongo-express
    restart: unless-stopped
    ports:
      - 8081:8081
    env_file:
      - .env
    depends_on:
      - mongo

volumes:
  data: