apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/name: agent
    app.kubernetes.io/instance: service
    app.kubernetes.io/component: agent
    app.kubernetes.io/part-of: agent
  name: agent
spec:
  ports:
  - name: agent
    protocol: TCP
    port: 9090
  selector:
    app.kubernetes.io/part-of: agent
    app.kubernetes.io/name: agent
#---
#apiVersion: v1
#kind: PersistentVolumeClaim
#metadata:
#  name: agent-data
#  labels:
#    app.kubernetes.io/name: agent-data
#    app.kubernetes.io/instance: pvc
#    app.kubernetes.io/component: agent
#    app.kubernetes.io/part-of: agent
#spec:
#  accessModes:
#    - ReadWriteOnce
#  resources:
#    requests:
#      storage: 5Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/name: agent
    app.kubernetes.io/instance: deployment
    app.kubernetes.io/component: agent
    app.kubernetes.io/part-of: agent
  name: agent
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: agent
  replicas: 1
  template:
    metadata:
      labels:
        app.kubernetes.io/name: agent
        app.kubernetes.io/instance: deployment
        app.kubernetes.io/component: agent
        app.kubernetes.io/part-of: agent
    spec:
      securityContext:
        runAsUser: 1000
        runAsGroup: 1000
        fsGroup: 1000
      initContainers:
        - name: init-redis-queue
          image: cloud.canister.io:5000/ale8193/busybox
          command: ['sh', '-c', "until nslookup redis.$(cat /var/run/secrets/kubernetes.io/serviceaccount/namespace).svc.cluster.local; do echo waiting for redis service; sleep 2; done"]
        - name: init-redis-shared-memory
          image: cloud.canister.io:5000/ale8193/busybox
          command: [ 'sh', '-c', "until nslookup redis-shared-memory.$(cat /var/run/secrets/kubernetes.io/serviceaccount/namespace).svc.cluster.local; do echo waiting for redis service; sleep 2; done" ]
      containers:
#        - image: cloud.canister.io:5000/ale8193/filebeat:7.9.3
#          name: filebeat
#          env:
#            - name: ELK_HOST
#              value: astaffolani.imolab.it
#            - name: ELASTICSEARCH_HOSTS
#              value: astaffolani.imolab.it:9200
#            - name: ENV_HOST
#              valueFrom:
#                fieldRef:
#                  fieldPath: metadata.namespace
#          envFrom:
#            - secretRef:
#                name: elasticsearch-secret
#          volumeMounts:
#            - mountPath: /var/log/agent
#              name: logs
#            - name: filebeat-config
#              mountPath: /usr/share/filebeat/filebeat.yml
#              subPath: filebeat.yml
#              readOnly: true
#          securityContext:
#            runAsUser: 0
#          resources:
#            limits:
#              memory: 200Mi
#            requests:
#              cpu: 100m
#              memory: 100Mi
        - image: cloud.canister.io:5000/ale8193/agent
          name: agent
          imagePullPolicy: Always
          ports:
            - containerPort: 9090
          env:
            - name: AGENT_SERVER_MODULE
              value: rlq_scheduler.agent.server
            - name: AGENT_SERVER_CONFIG_FILENAME
              value: /opt/rlq/agent/config/agent.yml
            - name: GLOBAL_CONFIG_FILENAME
              value: /opt/rlq/agent/config/global.yml
            - name: BROKER_SERVICE_SERVICE_HOST
              value: redis.default
          envFrom:
            - secretRef:
                name: minio-secret
            - configMapRef:
                name: minio-config
            - configMapRef:
                name: mongo-config
            - secretRef:
                name: mongo-secret
          volumeMounts:
            - mountPath: /opt/rlq/agent/logs/agent
              name: logs
              readOnly: false
            - name: global-config
              mountPath: /opt/rlq/agent/config/global.yml
              subPath: global.yml
              readOnly: true
            - name: agent-config
              mountPath: /opt/rlq/agent/config/agent.yml
              subPath: agent.yml
              readOnly: true
      volumes:
        - name: logs
          emptyDir: {}
        - name: global-config
          configMap:
            name: global-config
        - name: agent-config
          configMap:
            name: agent-config
#        - name: filebeat-config
#          configMap:
#            name: filebeat-config
      imagePullSecrets:
        - name: docker-registry