---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/name: task_broker
    app.kubernetes.io/instance: task_broker
    app.kubernetes.io/component: task_broker
    app.kubernetes.io/part-of: backbone
  name: task-broker
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: task_broker
  replicas: 1
  template:
    metadata:
      labels:
        app.kubernetes.io/name: task_broker
        app.kubernetes.io/instance: task_broker
        app.kubernetes.io/component: task_broker
        app.kubernetes.io/part-of: backbone
    spec:
      initContainers:
        - name: init-redis-queue
          image: cloud.canister.io:5000/ale8193/busybox
          command: ['sh', '-c', "until nslookup redis.$(cat /var/run/secrets/kubernetes.io/serviceaccount/namespace).svc.cluster.local; do echo waiting for redis service; sleep 2; done"]
        - name: init-redis-shared-memory
          image: cloud.canister.io:5000/ale8193/busybox
          command: [ 'sh', '-c', "until nslookup redis-shared-memory.$(cat /var/run/secrets/kubernetes.io/serviceaccount/namespace).svc.cluster.local; do echo waiting for redis service; sleep 2; done" ]
      containers:
#        - image: cloud.canister.io:5000/ale8193/filebeat:7.9.3
#          name: filebeat
#          env:
#            - name: ELK_HOST
#              value: astaffolani.imolab.it
#            - name: ELASTICSEARCH_HOSTS
#              value: astaffolani.imolab.it:9200
#            - name: ENV_HOST
#              valueFrom:
#                fieldRef:
#                  fieldPath: metadata.namespace
#          envFrom:
#            - secretRef:
#                name: elasticsearch-secret
#          volumeMounts:
#            - mountPath: /var/log/celery
#              name: logs
#            - name: filebeat-config
#              mountPath: /usr/share/filebeat/filebeat.yml
#              subPath: filebeat.yml
#              readOnly: true
#          securityContext:
#            runAsUser: 0
#          resources:
#            limits:
#              memory: 200Mi
#            requests:
#              cpu: 100m
#              memory: 100Mi
        - image: cloud.canister.io:5000/ale8193/task_broker
          name: task-broker
          imagePullPolicy: Always
          env:
            - name: CELERY_APP
              value: rlq_scheduler
            - name: BROKER_SERVICE_SERVICE_HOST
              value: redis.default
            - name: WORKER_NAME
              value: task_broker
            - name: WORKER_QUEUES
              value: main
          envFrom:
            - secretRef:
                name: minio-secret
            - configMapRef:
                name: minio-config
            - configMapRef:
                name: mongo-config
            - secretRef:
                name: mongo-secret
          volumeMounts:
            - mountPath: /var/log/celery
              name: logs
            - name: global-config
              mountPath: /opt/rlq/task_broker/config/global.yml
              subPath: global.yml
              readOnly: true
      volumes:
        - name: logs
          emptyDir: {}
        - name: global-config
          configMap:
            name: global-config
#        - name: filebeat-config
#          configMap:
#            name: filebeat-config
      imagePullSecrets:
        - name: docker-registry
